FROM alpine:latest as berkelydb

COPY ./install_db4.sh /root/install_db4.sh

RUN /root/install_db4.shRUN add-apt-repository ppa:bitcoin/bitcoin

                                                                              RUN apt-get update

                                                                              RUN apt-get install -y libdb4.8-dev libdb4.8++-dev